name: LMeX_UnitTests

on:
    workflow_dispatch:
##    schedule:
##        - cron: '0 2 * * *'

jobs:
    UnitsTest:
        name: Test1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: System Dependencies
          run: .github/workflows/dependencies/systemDeps.sh
        - name: LMeX Dependencies
          run: .github/workflows/dependencies/peleDeps.sh
        - name: Append
          run: echo "NewT" >> UnitTests/README.md
        - name: Commit results
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add UnitTests/README.md
            git commit -m 'Append to UnitTest' || echo "No changes to commit"
            git push origin || echo "No changes to commit"
